version: "3.8"
services:
    nest:
        image: node:16
        container_name: websocket-simple-chat-nest
        restart: "no"
        logging:
            options:
                max-size: "50m"
        environment:
          - PORT=8080
          - WS_PORT=8081
          - HOST=0.0.0.0
        ports:
          - 3000:8080
          - 3001:8081
          
        volumes:
          - ./websocket-nest:/app
        command: bash -c "echo installing packages && npm install --prefix=/app && echo launching && npm run start:dev --prefix=/app"
    angular:
        image: node:16
        container_name: websocket-simple-chat-angular
        restart: "no"
        logging:
            options:
                max-size: "50m"
        ports:
          - 4200:4200
        volumes:
          - ./websocket-angular:/app
        command: bash -c "echo installing packages && npm install --prefix=/app && echo launching && npm run start --prefix=/app"